<template>
  <div>
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-800 mb-2">Araç Listesi</h1>
      <p class="text-gray-600">
        Envanterdeki tüm araçları görüntüleyin ve yönetin
      </p>
    </div>

    <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
      <p class="text-yellow-800">
        🚧 <strong>Bu sayfa AI ile üretilecek</strong> - VehicleList.vue component'i docs/prompts/ içindeki prompt'lar kullanılarak oluşturulacak
      </p>
    </div>

    <div class="bg-white rounded-lg shadow-md p-6">
      <h2 class="text-xl font-semibold mb-4">Placeholder Liste</h2>
      <p class="text-gray-500 mb-4">
        AI asistanları aşağıdaki özellikleri ekleyecek:
      </p>
      <ul class="list-disc list-inside text-gray-600 space-y-2">
        <li>Araç listesi tablosu (VIN, Marka, Model, Fiyat)</li>
        <li>Filtreleme ve sıralama</li>
        <li>Pagination</li>
        <li>Detay görüntüleme</li>
        <li>API entegrasyonu</li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
// Vehicle list page - To be generated by AI
useHead({
  title: 'Araç Listesi - Araç Envanter Yönetimi'
})
</script>
