<template>
  <div>
    <div class="mb-8">
      <h1 class="text-3xl font-bold text-gray-800 mb-2">Yeni Araç Ekle</h1>
      <p class="text-gray-600">
        Envantere yeni araç kaydı oluşturun
      </p>
    </div>

    <div class="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
      <p class="text-yellow-800">
        🚧 <strong>Bu sayfa AI ile üretilecek</strong> - VehicleForm.vue component'i docs/prompts/ içindeki prompt'lar kullanılarak oluşturulacak
      </p>
    </div>

    <div class="bg-white rounded-lg shadow-md p-6">
      <h2 class="text-xl font-semibold mb-4">Placeholder Form</h2>
      <p class="text-gray-500 mb-4">
        AI asistanları aşağıdaki özellikleri ekleyecek:
      </p>
      <ul class="list-disc list-inside text-gray-600 space-y-2">
        <li>VIN numarası input ve validasyonu</li>
        <li>Marka/Model seçimi</li>
        <li>Yıl, motor tipi, renk inputları</li>
        <li>Fiyat bilgileri (alış/satış)</li>
        <li>Donatım özellikleri</li>
        <li>Form validasyonu (FluentValidation benzeri)</li>
        <li>API POST request</li>
        <li>Başarı/hata bildirimleri</li>
      </ul>

      <div class="mt-6 p-4 bg-blue-50 rounded-lg">
        <h3 class="font-semibold text-blue-800 mb-2">Referans Dokümanlar:</h3>
        <ul class="text-sm text-blue-700 space-y-1">
          <li>→ docs/business/US-001-add-vehicle-to-inventory.md</li>
          <li>→ docs/ui/vehicle-add-form.html</li>
          <li>→ docs/prompts/03-create-vue-component.md</li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Vehicle form page - To be generated by AI
useHead({
  title: 'Yeni Araç Ekle - Araç Envanter Yönetimi'
})
</script>
